[project]
name = "lthwpostgresql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "psycopg>=3.1.20",
    "psycopg2>=2.9.9",
    "python-dotenv>=0.21.1",
]
